# -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag

# docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=mysecretpassword -d mariadb

mysql:
  image: mariadb
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=my-secret-pw


