ldap_data:
  image: busybox
  volumes:
  - /etc/ldap/slapd.d
  - /var/lib/ldap
  mem_limit: 128m

ldap:
  image: osixia/openldap
  volumes_from:
  - ldap_data
  ports:
  - "389:389"
  - "636:636"
  mem_limit: 256m
  env_file: env

#  -h ldap.my-compagny.com

